from easydict import EasyDict

main_config = dict(
    exp_name='cartpole_dqn_bc_collect',
    env=dict(
        manager=dict(
            episode_num=float('inf'),
            max_retry=1,
            retry_type='reset',
            auto_reset=True,
            step_timeout=None,
            reset_timeout=None,
            retry_waiting_time=0.1,
            cfg_type='BaseEnvManagerDict',
            type='base',
        ),
        stop_value=195,
        n_evaluator_episode=5,
        collector_env_num=8,
        evaluator_env_num=5,
        replay_path='cartpole_dqn_seed0/video',
    ),
    policy=dict(
        model=dict(
            encoder_hidden_size_list=[128, 128, 64],
            obs_shape=4,
            action_shape=2,
            dueling=True,
        ),
        learn=dict(
            learner=dict(
                train_iterations=1000000000,
                dataloader=dict(
                    num_workers=0,
                ),
                log_policy=True,
                hook=dict(
                    load_ckpt_before_run='',
                    log_show_after_iter=100,
                    save_ckpt_after_iter=10000,
                    save_ckpt_after_run=True,
                ),
                cfg_type='BaseLearnerDict',
            ),
            update_per_collect=5,
            batch_size=64,
            learning_rate=0.001,
            target_update_freq=100,
            target_theta=0.005,
            ignore_done=False,
        ),
        collect=dict(
            collector=dict(
                deepcopy_obs=False,
                transform_obs=False,
                collect_print_freq=100,
                cfg_type='SampleSerialCollectorDict',
                type='sample',
            ),
            n_sample=8,
            unroll_len=1,
        ),
        eval=dict(
            evaluator=dict(
                eval_freq=40,
                render={'render_freq': -1, 'mode': 'train_iter'},
                cfg_type='InteractionSerialEvaluatorDict',
                stop_value=195,
                n_episode=5,
            ),
        ),
        other=dict(
            replay_buffer=dict(
                replay_buffer_size=20000,
                max_use=float('inf'),
                train_iter_per_log=100,
                priority=False,
                priority_IS_weight=False,
                priority_power_factor=0.6,
                IS_weight_power_factor=0.4,
                IS_weight_anneal_train_iter=100000,
                priority_max_limit=1000,
                cfg_type='DequeBufferWrapperDict',
                type='deque',
                import_names=['ding.data.buffer.deque_buffer_wrapper'],
            ),
        ),
        on_policy=False,
        cuda=False,
        multi_gpu=False,
        bp_update_sync=True,
        traj_len_inf=False,
        priority=False,
        priority_IS_weight=False,
        discount_factor=0.97,
        nstep=1,
        cfg_type='DQNPolicyDict',
        load_path='cartpole_dqn_seed0/ckpt/ckpt_best.pth.tar',
    ),
)
main_config = EasyDict(main_config)
main_config = main_config
create_config = dict(
    env=dict(
        type='cartpole',
        import_names=['dizoo.classic_control.cartpole.envs.cartpole_env'],
    ),
    env_manager=dict(
        cfg_type='BaseEnvManagerDict',
        type='base',
    ),
    policy=dict(type='dqn'),
)
create_config = EasyDict(create_config)
create_config = create_config
